<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SoundJournal.Domain\SoundJournal.Domain.csproj" />
    <ProjectReference Include="..\SoundJournal.Infrastructure\SoundJournal.Infrastructure.csproj" />
  </ItemGroup>

</Project>
